Dockerizing our RESTfull API Application

diff --git a/.github/workflows/continuous-deployment.yml b/.github/workflows/continuous-deployment.yml
--- a/.github/workflows/continuous-deployment.yml
+++ b/.github/workflows/continuous-deployment.yml
@@ -36,29 +36,15 @@ jobs:
       run: mvn clean package  -DforkCount=0 -e
 
     - name: Run tests
-      run: mvn test -e 
+      run: mvn test -e
 
     - name: Show Surefire reports
       if: always()
       run: |
         echo "===== SUREFIRE REPORTS ====="
         find target/surefire-reports -type f -name "*.txt" -print
-        echo "===== CONTENT ====="
-        for file in target/surefire-reports/*.txt; do
-          echo "===== $file ====="
-          cat "$file"
-        done- name: Show test reports
-      if: always()
-      working-directory: ./28_DockerizingOurApp
-      run: |
-        echo "===== SUREFIRE REPORTS ====="
-        find target/surefire-reports -type f -print || true
-
-        echo "===== TXT REPORTS ====="
-        cat target/surefire-reports/*.txt || true
-
-        echo "===== FAILURES AND ERRORS ====="
-        grep -R -i -E "failure|error|403|401|cors|invalid cors" target/surefire-reports || true
+        echo "===== FAILED TEST DETAILS ====="
+        grep -R -A 20 -B 5 "Failures\|Errors\|Exception\|ERROR" target/surefire-reports/*.txt || true
 
     - name: Docker Compose Build
       working-directory: ./28_DockerizingOurApp
